name: h2spec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  conformance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ae195bbe749a7cef685ac729197124a48305c1cb # v1.276.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem --version
          gem install bundler
          bundle --version
          bundle install
      - name: Install h2spec
        run: |
          set -eu
          curl -Ls https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz | tar xz
          mkdir -p $GITHUB_WORKSPACE/bin
          mv h2spec  $GITHUB_WORKSPACE/bin/h2spec
          chmod +x $GITHUB_WORKSPACE/bin/h2spec
          echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - name: Run conformance test
        run: bundle exec rake conformance
      - uses: mikepenz/action-junit-report@a294a61c909bd8a4b563024a2faa28897fd53ebc # v6.1.0
        if: success()
        with:
          report_paths: conformance/reports/h2spec.xml
